const {
  PROXY_PATH_PREFIX,
  PROXY_ROUTES,
  OPENAI_COMPATIBLE_ROUTE_PATTERNS,
  STATIC_PROXY_ROUTES,
} = require('./proxy-routes.cjs');

exports.PROXY_PATH_PREFIX = PROXY_PATH_PREFIX;
exports.PROXY_ROUTES = PROXY_ROUTES;
exports.OPENAI_COMPATIBLE_ROUTE_PATTERNS = OPENAI_COMPATIBLE_ROUTE_PATTERNS;
exports.STATIC_PROXY_ROUTES = STATIC_PROXY_ROUTES;
exports.resolveProxyPath = (routeId) => PROXY_ROUTES[routeId];
